### PR TITLE
Adding python conversion for TOML and YAML

### PR DESCRIPTION
**Pull request by chiqomar**
Hi all, I'm back to update my project to add YAML and TOML, and this one works quite well.
No python, but have replaced it with an awesome Rust-based project, [RQ](https://github.com/dflemstr/rq), that does the same thing, and after doing a UPX, pack, only adds 1.8MB more to the image.
I would like to test this a bit more, but I think the changes are minimal enough that it should work (if the base library docker image works the same way).

### CODE REVIEW

**Comment by chiqomar** [comment]
@tlvu I thought I did PR against origin? Also, yes, I went ahead and pushed this to my `chiqomar/crontab`, so it should be ready to use. Haven't tagged a version just yet, thinking just for testing at the moment. I have it working in our prod environment right now.

**Review by willfarrell — APPROVED** [review]

**Comment by willfarrell** [comment]
Everything looks good to me. let me know how testing goes and I'll knock out a v1 release.

**Comment by chiqomar** [comment]
@willfarrell I meant to update this earlier, I apologize for the extra changes.
- README is now updated, stating the changes made
- Added a parsing for JSON documents to match the behavior of the TOML and YAML docs (supporting both arrays and mappings)
- Put samples into a `config-samples` folder, so they don't crowd up root.

I am currently using this in production, and it is deployed and working with a TOML config. If you're okay with the latest changes, go ahead with the release.

**Review by willfarrell — APPROVED** [review]

**Comment by willfarrell** [comment]
Apologies not necessary, thank you for taking the time to put this together. Everything looks good. I'll leave this open for a bit to allow others to comment.

**Comment by kbadk** [comment]
This merge has broken crontab for me. UPX does not exist in Alpine for ARM64 (Raspberry Pi 4, 64 bit).

```
$ sudo docker run -it alpine apk add --update upx
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/aarch64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/aarch64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  upx (missing):
    required by: world[upx]
```

But even if UPX was available, I don't think it's suitable here. [UPX reduces disk usage slightly, but at the cost of memory consumption](https://stackoverflow.com/a/9219696/453331). Disk space is much cheaper than memory.

On top of that, even if installing UPX wouldn't fail, I imagine pulling a x86_64 binary of `rq` won't go well either for lots of users.

This is also not [the recommended way of installing `rq`](https://github.com/dflemstr/rq/blob/master/doc/installation.md).

Also, I'm not convinced using [`tini`](https://github.com/krallin/tini) to run the entrypoint bash script does of any good.

Lastly, the code has several lines of code commented out, presuambly from debugging, and I'm also not a huge fan of replacing the error message `Unable to find ${HOME_DIR}/config.json` with the less informative `NO CONFIG FILE FOUND` which appears to be the case in certain scenarios.

**Comment by kbadk** [comment]
This merge has broken crontab for me. UPX does not exist in Alpine for ARM64 (Raspberry Pi 4, 64 bit).

```
$ sudo docker run -it alpine apk add --update upx
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/aarch64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/aarch64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  upx (missing):
    required by: world[upx]
```

But even if UPX was available, I don't think it's suitable here. [UPX reduces disk usage slightly, but at the cost of memory consumption](https://stackoverflow.com/a/9219696/453331). Disk space is much cheaper than memory.

On top of that, even if installing UPX wouldn't fail, I imagine pulling a x86_64 binary of `rq` won't go well either for lots of users.

This is also not [the recommended way of installing `rq`](https://github.com/dflemstr/rq/blob/master/doc/installation.md).

I'm not convinced using [`tini`](https://github.com/krallin/tini) to run the entrypoint bash script will do us any good.

Lastly, the code has several lines of code commented out, presuambly from debugging, and I'm also not a huge fan of replacing the error message `Unable to find ${HOME_DIR}/config.json` with the less informative `NO CONFIG FILE FOUND` which appears to be the case in certain scenarios.

**Comment by willfarrell** [comment]
Thank you for reporting. I had a feeling this may happen, which is why the tag `0.6.0` still exists. 

I'm good with `tini` being removed. How about something like this (should have better multi-arch support too):

```Dockerfile
FROM alpine:3.12 as rq-build

ENV RQ_VERSION=1.0.2
WORKDIR /root/

RUN apk add --no-cache cargo \
    && cargo install record-query --version ${RQ_VERSION}

FROM library/docker:stable

COPY --from=rq-build /root/rq /usr/local/bin

ENV HOME_DIR=/opt/crontab
RUN apk add --no-cache --virtual .run-deps gettext jq bash \
    && mkdir -p ${HOME_DIR}/jobs ${HOME_DIR}/projects \
    && adduser -S docker -D

COPY docker-entrypoint /
ENTRYPOINT ["/docker-entrypoint"]

HEALTHCHECK --interval=5s --timeout=3s \
    CMD ps aux | grep '[c]rond' || exit 1

CMD ["crond", "-f", "-d", "6", "-c", "/etc/crontabs"]
```

I no longer use this container (running mostly all serverless these days). If you like to to submit the above with any other changes you think would have value to others using it. I'd be happy to review and merge this week.

**Pull request merged**
